fix: enable calling `squashfs-root/AppRun` with a relative path (#390)
When playing around with this and following the [AppImage inspection
instructions](https://github.com/lalten/rules_appimage/tree/main?tab=readme-ov-file#something-isnt-right-about-my-appimage-how-can-i-debug),
I ran into

```sh
$ ./examples/integration_test.sh  # with the `trap` command commented out
$ ./examples/hello.appimage --appimage-extract
$ $(realpath ./squashfs-root/AppRun)                                                                                                                 
Hello, World
$ ./squashfs-root/AppRun
Traceback (most recent call last):
  File "/home/chris/rules_appimage/squashfs-root/hello.runfiles/_main/_hello_stage2_bootstrap.py", line 499, in <module>
    main()
  File "/home/chris/rules_appimage/squashfs-root/hello.runfiles/_main/_hello_stage2_bootstrap.py", line 493, in main
    _run_py_path(main_filename, args=sys.argv[1:])
  File "/home/chris/rules_appimage/squashfs-root/hello.runfiles/_main/_hello_stage2_bootstrap.py", line 287, in _run_py_path
    runpy.run_path(main_filename, run_name="__main__")
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/chris/rules_appimage/squashfs-root/hello.runfiles/_main/hello.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

When you run `./squashfs-root/AppRun` with a relative path,
`thisdir="${0%/*}"` from
[here](https://github.com/cbachhuber/rules_appimage/blob/1a60854a1c75880316dad104486475705fdf3285/appimage/private/mkapprun.bzl#L71)
produces the relative path `./squashfs-root`. Then `RUNFILES_DIR` is set
to the relative `./squashfs-root/hello.runfiles`. After the `cd
"$workdir"` that follows, that relative path is no longer resolvable
from the new CWD — so `rules_python` can't find the venv/packages and
`click` is missing. I guess this applies to any runfiles, independent of
language.

When the AppImage runs normally (FUSE-mounted), `$0` is always an
absolute path, so this doesn't trigger.